In [23]:
import requests
import pandas as pd

from config import APP_ID, APP_KEY
import requests

url = (
    f"https://api.adzuna.com/v1/api/jobs/au/search/1"
    f"?app_id={APP_ID}"
    f"&app_key={APP_KEY}"
    f"&results_per_page=50"
    f"&what=data+scientist"
)

response = requests.get(url)

data = response.json()

print("Status Code:", response.status_code)

Status Code: 200

In [24]:
print(data.keys())

dict_keys(['results', 'mean', 'count', '__CLASS__'])

In [25]:
jobs = []

for job in data["results"]:
    jobs.append({
        "title": job.get("title"),
        "company": job.get("company", {}).get("display_name"),
        "location": job.get("location", {}).get("display_name"),
        "salary_min": job.get("salary_min"),
        "salary_max": job.get("salary_max"),
        "description": job.get("description"),
        "created": job.get("created")
    })

df = pd.DataFrame(jobs)

df.head()

,title,company,location,salary_min,salary_max,description,created
0,Data Scientist- Marketing,AMP,"The Rocks, Sydney",NaN,NaN,This is a Data Scientist- Marketing role with ...,2025-12-13T12:08:36Z
1,Data Scientist,Doordash,"Banksia, Rockdale Area",NaN,NaN,This is a Data Scientist role with Doordash ba...,2026-05-26T14:41:20Z
2,Lead Data Scientist,Lendi Group,"The Rocks, Sydney",NaN,NaN,This is a Lead Data Scientist role with Lendi ...,2026-03-26T15:31:49Z
3,Graduate Data Science,Mineral Resources Limited,"Perth CBD, Perth",NaN,NaN,This is a Graduate Data Science role with Mine...,2026-03-07T15:16:54Z
4,Senior Data Scientist,Ingrity,"The Rocks, Sydney",NaN,NaN,This is a Senior Data Scientist role with Ingr...,2026-03-16T15:52:18Z

In [26]:
df = pd.DataFrame(jobs)

print(len(df))

df.head()

50

,title,company,location,salary_min,salary_max,description,created
0,Data Scientist- Marketing,AMP,"The Rocks, Sydney",NaN,NaN,This is a Data Scientist- Marketing role with ...,2025-12-13T12:08:36Z
1,Data Scientist,Doordash,"Banksia, Rockdale Area",NaN,NaN,This is a Data Scientist role with Doordash ba...,2026-05-26T14:41:20Z
2,Lead Data Scientist,Lendi Group,"The Rocks, Sydney",NaN,NaN,This is a Lead Data Scientist role with Lendi ...,2026-03-26T15:31:49Z
3,Graduate Data Science,Mineral Resources Limited,"Perth CBD, Perth",NaN,NaN,This is a Graduate Data Science role with Mine...,2026-03-07T15:16:54Z
4,Senior Data Scientist,Ingrity,"The Rocks, Sydney",NaN,NaN,This is a Senior Data Scientist role with Ingr...,2026-03-16T15:52:18Z

In [29]:
df.to_csv("data/raw/jobs.csv", index=False)

print("File saved")

File saved

In [28]:
import os

print(os.path.exists("data/raw/jobs.csv"))

False